#!/bin/bash

git config --global user.name "Grace Quinn"
git config --global user.email "your.email@example.com"
git config --global init.defaultBranch main
git config --global core.editor "vim"
git config --global color.ui auto
git config --global pull.rebase true
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/libexec/git-core/git-credential-manager.exe"
