containerLogs:
  fluentBit:
    config: 
      extraFiles:
        gitlab-logs.conf: |
          [INPUT]
            Name                     tail
            Tag                      gitlab.tail
            Path                     /var/log/containers/netshoot*
            parser                   json
            Read_from_Head           ${READ_FROM_HEAD}

          [FILTER]
            Name                     rewrite_tag
            Match                    gitlab.tail
            Rule                     $subcomponent ^(api_json)$ from.$TAG.api false
            Rule                     $subcomponent ^(application_json)$ from.$TAG.app false
            Rule                     $subcomponent ^(audit_json)$ from.$TAG.audit false
            Rule                     $subcomponent ^(production_json)$ from.$TAG.prod false
            Emitter_Name             rewrite_gitlab_log_tag


          [OUTPUT]
            Name                     cloudwatch_logs
            Match                    from.gitlab.tail.api
            region                   ${AWS_REGION}
            log_group_name           /some-prefix/gitlab-api
            log_stream_prefix        ${HOST_NAME}-
            log_retention_days       30
            auto_create_group        true
            extra_user_agent         container-insights

          [OUTPUT]
            Name                     cloudwatch_logs
            Match                    from.gitlab.tail.app
            region                   ${AWS_REGION}
            log_group_name           /some-prefix/gitlab-app
            log_stream_prefix        ${HOST_NAME}-
            log_retention_days       30
            auto_create_group        true
            extra_user_agent         container-insights

          [OUTPUT]
            Name                     cloudwatch_logs
            Match                    from.gitlab.tail.audit
            region                   ${AWS_REGION}
            log_group_name           /some-prefix/gitlab-audit
            log_stream_prefix        ${HOST_NAME}-
            log_retention_days       30
            auto_create_group        true
            extra_user_agent         container-insights

          [OUTPUT]
            Name                     cloudwatch_logs
            Match                    from.gitlab.tail.prod
            region                   ${AWS_REGION}
            log_group_name           /some-prefix/gitlab-prod
            log_stream_prefix        ${HOST_NAME}-
            log_retention_days       30
            auto_create_group        true
            extra_user_agent         container-insights

        customParsers: |
          [PARSER]
            Name               decode_json
            Format             json
            Time_Key           time
            Time_Format        %Y-%m-%dT%H:%M:%S.%L
            Time_Keep          On
            Decode_Field_As    json log
