#!/bin/bash

set -ex

sudo usermod -aG systemd-journal newan # Add user to journald group to run systemctl commands
sudo tee /etc/systemd/system/fb-test.service > /dev/null << EOF
[Unit]
Description=Fluent Bit test service
[Service]
ExecStart=/usr/bin/bash -c 'while true; do echo -e "Line 1\nLine2\nLine 3"; sleep 10; done'
StandardOutput=journal
Restart=always
EOF

sudo systemctl daemon-reexec
sudo systemctl daemon-reload
sudo systemctl start fb-test.service
sudo systemctl status fb-test.service
sudo journalctl -u fb-test.service --no-pager
