#!/bin/bash

# VS Code's debugger does not automatically inherit the shell environment (AWS credentials)
# This script passes the variables through. It exports current credentials into .envrc.local, 
# and passes to the launch.json envFile.

# NOTE: there's no validation checks/expectations set
loginParams=("AWS_SESSION_TOKEN" "AWS_SECRET_ACCESS_KEY" "AWS_ACCESS_KEY_ID")

for param in "${loginParams[@]}"; do
  value="${!param}"
  echo "export ${param}=${value}" >> .envrc.local
done
